### ISSUE TITLE
Stuck deploying on vsphere via ova

### ISSUE THREAD

**Issue by dandunckelman** [vmware/simple-k8s-test-env#8]
I'm following the [provision-on-vsphere-with-ova doc](https://github.com/vmware/simple-k8s-test-env/blob/master/ova/doc/provision-on-vsphere-with-ova.md) and imported the OVA like this:

```
VC=vcenter
USER=administrator@vsphere.local
PASS=pass
DC1=my_domain_controller1
DC2=my_domain_controller2
OVA=/path/to/sk8-photon.ova
DC=datacenter
CLUSTER=cluster
HOST=esx
DS=datastore
NAME=k8s
OVA_NET=sddc-cgw-network-3
TA_NET=my-network

ovftool --acceptAllEulas \
        --allowExtraConfig \
        --datastore=$DS \
        --disableVerification \
        --diskMode=thin \
        --machineOutput \
        --noSSLVerify \
        --name=$NAME \
        --net:$OVA_NET=$TA_NET \
        --powerOn \
        --prop:CLOUD_PROVIDER_TYPE=In-tree \
        --prop:K8S_VERSION=release/stable \
        --prop:NETWORK_DNS_1=$DC1 \
        --prop:NETWORK_DNS_2=$DC2 \
        --prop:NUM_BOTH=1 \
        --prop:NUM_CONTROLLERS=2 \
        --prop:NUM_NODES=3 \
        --prop:VSPHERE_PASSWORD=$PASS \
        --prop:VSPHERE_SERVER=$VC \
        --prop:VSPHERE_USER=$USER \
        --skipManifestCheck \
        $OVA \
        vi://$USER:$PASS@$VC/$DC/host/$CLUSTER/$HOST
```

after some time, the 3 VMs are up and running. But when I run this:

    curl -sSL http://bit.ly/sk8-local | sh -s -- MYUUID

I get this:

    getting cluster information                                        
      * id                          govc: specify an ESX or vCenter URL

Please help me find the little detail I missed.
- Do I need to set another OVF property? Is one incorrect?
- Is `In-tree` the right `CLOUD_PROVIDER_TYPE` for my on-prem vcenter/esx setup?
  - BTW, I'm on vcenter 6.7.0.20000 and ESXi 6.7.0 10302608

Thanks.

**Comment by akutz** [comment]
Hi @dandunckelman,

Hmm, I've never tried deploying things with the `ovftool` program, but sure, that should work. The valid values for `CLOUD_PROVIDER_TYPE` in the OVF properties are `External` and `In-tree`, so you should be good there. FWIW, here's the code ([link](https://github.com/vmware/simple-k8s-test-env/blob/f23ee857f2cc9fc095486b2ccf3026736537875d/ova/sk8-vsphere.sh#L117-L130)) that checks that:

```shell
# Determine if the vSphere cloud provider should be deployed.
cloud_provider_type="$(rpc_get CLOUD_PROVIDER_TYPE)"
if echo "${cloud_provider_type}" | grep -iq 'none'; then
  info "no cloud provider selected"
  exit 0
elif echo "${cloud_provider_type}" | grep -iq 'in-tree'; then
  info "configuring in-tree cloud provider"
  cloud_provider_type=in-tree
elif echo "${cloud_provider_type}" | grep -iq 'external'; then
  info "configuring external cloud provider"
  cloud_provider_type=external
else
  exit 0
fi
```

I definitely need to add a debugging section to the README. If you're able, please SSH or remote into the first VM and then copy the logs from `/var/log/sk8/` into a [GitHub gist](https://gist.github.com) or send them to me at akutz at VMware dot com as a tarball. I'll happily take a look :)

**Comment by dandunckelman** [comment]
@akutz I'd love to get that to you, but I don't know the user/pass to SSH into the VM.

Did I miss something in the documentation?

**Comment by akutz** [comment]
Hi @dandunckelman,

You can log in via the console with `root/changeme`. The OVA creates an SSH key/pair for you to use, and the init-local script, when working, should download that for you. Seems like it's failing before that part.

**Comment by dandunckelman** [comment]
@akutz tried to SSH but login fails. Probably is the exact problem your thinking.

Any other thoughts?

**Comment by akutz** [comment]
Hi @dandunckelman,

SSH doesn't support `root` access. Open the remote or web console to the VM through the vCenter UI. Log into the VM that way since it's "console" access.

**Comment by dandunckelman** [comment]
@akutz I misunderstood your saying console. Got in thru the web console in vsphere.

I'll have the logs for you soon.

**Comment by dandunckelman** [comment]
@akutz email sent.

**Comment by akutz** [comment]
Hi @dandunckelman,

Thank you. I see where the `sk8.log` shows it timed out waiting for the other nodes to join the cluster. Can you possibly ssh into the other two nodes as well? Because sk8 sets up SSH for you, you should, from `c01`, be able to simply `ssh c02` and `ssh w01` if DNS is working. If it's not, then you'll have to use the remote console again. Sorry about this. I just don't see the failure from these logs as it appears to have occurred on one of the other two nodes.

**Comment by dandunckelman** [comment]
@akutz email sent w/ logs from other 2 nodes.

Thanks again.

**Comment by akutz** [comment]
Hi @dandunckelman,

No worries, glad to help. This is a new one to me. From `w01/sk8.log`:

```shell
Error: context deadline exceeded
ERROR [1551394252] failed to obtain distributed lock:
Error: context deadline exceeded
ERROR [1551394254] failed to get lease id
Error: context deadline exceeded
ERROR [1551394256] failed to obtain distributed lock:
Error: context deadline exceeded
/var/lib/sk8/sk8.sh: line 775: /sk8/nodes/0: No such file or directory
ERROR [1551394258] failed to put contents of STDIN to etcd key '/sk8/nodes/0'
ERROR [1551394258] failed to put node info
INFO [1551394258] waiting on all nodes to join the cluster
.Error: context deadline exceeded
.Error: context deadline exceeded
.Error: context deadline exceeded
.Error: context deadline exceeded
.................................................................................................   ERROR [1551394573] timed out waiting for node info
FATAL [1551394573] failed to wait on all node info
```

Unfortunately I don't see *what* went wrong, only the result. How beefy is your vSphere cluster? The reason I ask is because if the nodes don't come up within 15 minutes, the information in etcd used to enable discovery times out:

```shell
# The number of seconds the keys associated with sk8 will exist
# before being removed by the etcd server.
#
# The default value is 15 minutes.
ETCD_LEASE_TTL=${ETCD_LEASE_TTL:-900}
```

It should hardly ever take longer than 15 minutes, but depending on network connection and the available compute resources, it *can*. To combat this you can use the OVF tool to deploy the OVA, but **not** power it on afterwards. Instead then use the `govc` command line tool to execute:

```shell
$ govc vm.change -e "guestinfo.sk8.ETCD_LEASE_TTL=3600" -vm.ipath PATH_TO_VM
```

This will instruct sk8 to use a one-hour lease for the discovery information in etcd instead of the default 15 minutes.

If that doesn't work I will set up a Zoom with you to see what's going on.

Also, in case I wasn't clear, you'll need to stand up a new cluster to try the longer TTL. Once the OVA boots, there's no easy way to reset it unless you deploy it, snapshot it prior to boot, and then power it on.

**Comment by dandunckelman** [comment]
@akutz it's a pretty hefty cluster of 8 esxi hosts with > 200 GHz CPU and 1TB RAM free.

I'll try a few things tomorrow based on your suggestions and report back ASAP.

Thanks again.

**Comment by dandunckelman** [comment]
@akutz not sure if it's a problem, but when I first power on the VM, I see this:

![image](https://user-images.githubusercontent.com/1153702/53912425-21151a00-4016-11e9-89d2-5a1b2129e7ee.png)

and it stays that way for ~5 minutes.

Eventually, it gets an IP and shows the login.

So, I login and start tailing the logs, but I ended up w/ the same result.

I'm going to try the change for ETCD_LEASE_TTL now.

**Comment by akutz** [comment]
Hi @dandunckelman,

I see the same thing, I don't think it's anything about which to be concerned.

**Comment by dandunckelman** [comment]
@akutz I tried that change, but it seems to have failed at about the same time.

I can do a call this Friday. I'm in the US Mountain timezone and available between 9:30AM - 5:30PM

Let me know what day/time works for you.

I really appreciate the help.

**Comment by dandunckelman** [comment]
Closing. We've abandoned this.
